vim.api.nvim_create_user_command('Cppath', function()
    local path = vim.fn.expand('%:p')
    vim.fn.setreg('+', path)
    vim.notify('Copied "' .. path .. '" to the clipboard!')
end, {})

vim.api.nvim_create_user_command('Cpname', function()
    local name = vim.fn.expand('%:t')
    vim.fn.setreg('+', name)
    vim.notify('Copied "' .. name .. '" to the clipboard!')
end, {})
