general.import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "OnlyLeft" # (macos) make option behave like Alt

[window.dimensions]
columns = 135
lines = 30

[window.class]
general = "Alacritty"
instance = "Alacritty"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]
