import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 135
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12
